try to run tests without installing pypi packages during docker build
Signed-off-by: udosson <r.klemens@yahoo.de>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -155,198 +155,198 @@ jobs:
           mkdir -p ${GITHUB_WORKSPACE}/cache
           touch ${GITHUB_WORKSPACE}/cache/${{ env.CACHE_KEY_BUILD }}
 
-  # lint-image:
-  #   name: Create Linter Image
-  #   # Reference to workflow-setup job is required to access its various outputs.
-  #   needs: workflow-setup
-  #   runs-on: ubuntu-latest
-  #   env:
-  #     CACHE_KEY_LINT: ${{ needs.workflow-setup.outputs.CACHE_KEY_LINT }}
-  #     GITHUB_REPOSITORY_NAME: ${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
-  #     UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
-  #   steps:
-  #     - name: Git checkout
-  #       uses: actions/checkout@v2
+  lint-image:
+    name: Create Linter Image
+    # Reference to workflow-setup job is required to access its various outputs.
+    needs: workflow-setup
+    runs-on: ubuntu-latest
+    env:
+      CACHE_KEY_LINT: ${{ needs.workflow-setup.outputs.CACHE_KEY_LINT }}
+      GITHUB_REPOSITORY_NAME: ${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
+      UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
+    steps:
+      - name: Git checkout
+        uses: actions/checkout@v2
 
-  #     - name: Try load from cache
-  #       id: cache-image
-  #       uses: actions/cache@v2
-  #       with:
-  #         path: ${GITHUB_WORKSPACE}/cache
-  #         key: ${{ env.CACHE_KEY_LINT }}
+      - name: Try load from cache
+        id: cache-image
+        uses: actions/cache@v2
+        with:
+          path: ${GITHUB_WORKSPACE}/cache
+          key: ${{ env.CACHE_KEY_LINT }}
 
-  #     - name: Prepare image labels and tags
-  #       if: steps.cache-image.outputs.cache-hit != 'true'
-  #       id: prep
-  #       shell: bash
-  #       run: |
-  #         DOCKER_IMAGE=ghcr.io/${{ env.GITHUB_REPOSITORY_NAME }}/plenum-lint
-  #         # ToDo - Update hard coded 'ubuntu-18-04' tag when integrating these flows with the ubuntu-20.04-upgrade branch.
-  #         TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:ubuntu-18-04"
-  #         echo ::set-output name=tags::${TAGS}
-  #         echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
+      - name: Prepare image labels and tags
+        if: steps.cache-image.outputs.cache-hit != 'true'
+        id: prep
+        shell: bash
+        run: |
+          DOCKER_IMAGE=ghcr.io/${{ env.GITHUB_REPOSITORY_NAME }}/plenum-lint
+          # ToDo - Update hard coded 'ubuntu-18-04' tag when integrating these flows with the ubuntu-20.04-upgrade branch.
+          TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:ubuntu-18-04"
+          echo ::set-output name=tags::${TAGS}
+          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
 
-  #     - name: Log into the GitHub Container Registry
-  #       if: steps.cache-image.outputs.cache-hit != 'true'
-  #       uses: docker/login-action@v1
-  #       with:
-  #         registry: ghcr.io
-  #         username: ${{ github.actor }}
-  #         password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Log into the GitHub Container Registry
+        if: steps.cache-image.outputs.cache-hit != 'true'
+        uses: docker/login-action@v1
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
 
-  #     - name: Set up Docker Buildx
-  #       if: steps.cache-image.outputs.cache-hit != 'true'
-  #       uses: docker/setup-buildx-action@v1
+      - name: Set up Docker Buildx
+        if: steps.cache-image.outputs.cache-hit != 'true'
+        uses: docker/setup-buildx-action@v1
 
-  #     - name: Build and push image
-  #       if: steps.cache-image.outputs.cache-hit != 'true'
-  #       uses: docker/build-push-action@v2
-  #       with:
-  #         context: .
-  #         file: .github/workflows/lint/Dockerfile.${{ env.UBUNTU_VERSION }}
-  #         no-cache: true
-  #         push: ${{ github.event_name != 'pull_request' }}
-  #         tags: ${{ steps.prep.outputs.tags }}
-  #         labels: |
-  #           org.opencontainers.image.source=${{ github.event.repository.html_url }}
-  #           org.opencontainers.image.created=${{ steps.prep.outputs.created }}
-  #           org.opencontainers.image.revision=${{ github.sha }}
+      - name: Build and push image
+        if: steps.cache-image.outputs.cache-hit != 'true'
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          file: .github/workflows/lint/Dockerfile.${{ env.UBUNTU_VERSION }}
+          no-cache: true
+          push: ${{ github.event_name != 'pull_request' }}
+          tags: ${{ steps.prep.outputs.tags }}
+          labels: |
+            org.opencontainers.image.source=${{ github.event.repository.html_url }}
+            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
+            org.opencontainers.image.revision=${{ github.sha }}
 
-  #     - name: Touch Cache
-  #       if: steps.cache-image.outputs.cache-hit != 'true'
-  #       run: |
-  #         # export GITHUB_REPOSITORY_NAME=$(echo ${GITHUB_REPOSITORY,,})
-  #         # echo ${{ secrets.CR_PAT }} | docker login ghcr.io --username ${{ secrets.CR_USER }} --password-stdin
-  #         # docker build -f .github/workflows/lint/Dockerfile.${{ env.UBUNTU_VERSION }} --no-cache -t ${{ env.GITHUB_REPOSITORY_NAME }}/plenum-lint:${{ env.CACHE_KEY_LINT }} .
-  #         # docker tag ${{ env.GITHUB_REPOSITORY_NAME }}/plenum-lint:${{ env.CACHE_KEY_LINT }} ghcr.io/${{ env.GITHUB_REPOSITORY_NAME }}/plenum-lint:${{ env.UBUNTU_VERSION }}
-  #         # docker push ghcr.io/${{ env.GITHUB_REPOSITORY_NAME }}/plenum-lint:${{ env.UBUNTU_VERSION }}
-  #         mkdir -p ${GITHUB_WORKSPACE}/cache
-  #         touch ${GITHUB_WORKSPACE}/cache/${{ env.CACHE_KEY_LINT }}
+      - name: Touch Cache
+        if: steps.cache-image.outputs.cache-hit != 'true'
+        run: |
+          # export GITHUB_REPOSITORY_NAME=$(echo ${GITHUB_REPOSITORY,,})
+          # echo ${{ secrets.CR_PAT }} | docker login ghcr.io --username ${{ secrets.CR_USER }} --password-stdin
+          # docker build -f .github/workflows/lint/Dockerfile.${{ env.UBUNTU_VERSION }} --no-cache -t ${{ env.GITHUB_REPOSITORY_NAME }}/plenum-lint:${{ env.CACHE_KEY_LINT }} .
+          # docker tag ${{ env.GITHUB_REPOSITORY_NAME }}/plenum-lint:${{ env.CACHE_KEY_LINT }} ghcr.io/${{ env.GITHUB_REPOSITORY_NAME }}/plenum-lint:${{ env.UBUNTU_VERSION }}
+          # docker push ghcr.io/${{ env.GITHUB_REPOSITORY_NAME }}/plenum-lint:${{ env.UBUNTU_VERSION }}
+          mkdir -p ${GITHUB_WORKSPACE}/cache
+          touch ${GITHUB_WORKSPACE}/cache/${{ env.CACHE_KEY_LINT }}
 
-  # indy_plenum_tests:
-  #   name: Sliced Module Tests
-  #   # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
-  #   needs: [workflow-setup, build-image]
-  #   runs-on: ubuntu-20.04
-  #   # Fix for scacap/action-surefire-report out of memory error:
-  #   # - https://github.com/ScaCap/action-surefire-report/issues/17
-  #   env:
-  #     NODE_OPTIONS: "--max_old_space_size=4096"
-  #     UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
-  #   container:
-  #     image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-build:${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
-  #   strategy:
-  #     matrix:
-  #       module: [plenum]
-  #       # To slice up the tests into smaller chunks add additional sequential
-  #       # numbers here.  The subsequent steps will adjust automatically.
-  #       # ${{ strategy.job-total }} is used to get the total number of slices.
-  #       slice: [1, 2, 3, 4, 5, 6, 7, 8]
-  #     fail-fast: false
-  #   steps:
-  #     - name: Check out code
-  #       uses: actions/checkout@v2
+  indy_plenum_tests:
+    name: Sliced Module Tests
+    # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
+    needs: [workflow-setup, build-image]
+    runs-on: ubuntu-20.04
+    # Fix for scacap/action-surefire-report out of memory error:
+    # - https://github.com/ScaCap/action-surefire-report/issues/17
+    env:
+      NODE_OPTIONS: "--max_old_space_size=4096"
+      UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
+    container:
+      image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-build:${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
+    strategy:
+      matrix:
+        module: [plenum]
+        # To slice up the tests into smaller chunks add additional sequential
+        # numbers here.  The subsequent steps will adjust automatically.
+        # ${{ strategy.job-total }} is used to get the total number of slices.
+        slice: [1, 2, 3, 4, 5, 6, 7, 8]
+      fail-fast: false
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
 
-  #     - name: Cache pip
-  #       uses: actions/cache@v2
-  #       with:
-  #         # pip cache on the plenum-build image is not in the default location.
-  #         # path: ~/.cache/pip
-  #         path: /root/.cache/pip
-  #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
-  #         restore-keys: |
-  #           ${{ runner.os }}-pip-
+      - name: Cache pip
+        uses: actions/cache@v2
+        with:
+          # pip cache on the plenum-build image is not in the default location.
+          # path: ~/.cache/pip
+          path: /root/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-
 
-  #     - name: Install dependencies
-  #       run: |
-  #         # Explicitly use the existing pip cache location in the plenum-build image.
-  #         pip --cache-dir /root/.cache/pip install .[tests]
+      - name: Install dependencies
+        run: |
+          # Explicitly use the existing pip cache location in the plenum-build image.
+          pip --cache-dir /root/.cache/pip install .[tests]
 
-  #     - name: Run Indy Plenum ${{ matrix.module }} test slice ${{ matrix.slice }}/${{ strategy.job-total }}
-  #       id: plenum-test
-  #       run: RUSTPYTHONASYNCIODEBUG=0 python3 runner.py --pytest "python3 -m pytest -l -vv" --dir "${{ matrix.module }}" --output "test-result-plenum-${{ matrix.slice }}.txt" --test-only-slice "${{ matrix.slice }}/${{ strategy.job-total }}"
+      - name: Run Indy Plenum ${{ matrix.module }} test slice ${{ matrix.slice }}/${{ strategy.job-total }}
+        id: plenum-test
+        run: RUSTPYTHONASYNCIODEBUG=0 python3 runner.py --pytest "python3 -m pytest -l -vv" --dir "${{ matrix.module }}" --output "test-result-plenum-${{ matrix.slice }}.txt" --test-only-slice "${{ matrix.slice }}/${{ strategy.job-total }}"
 
-  #     - name: Publish Test Report
-  #       if: success() || failure()
-  #       uses: scacap/action-surefire-report@v1.0.7
-  #       continue-on-error: true
-  #       with:
-  #         check_name: Indy Plenum ${{ matrix.module }} Test Report for slice ${{ matrix.slice }}/${{ strategy.job-total }}
-  #         github_token: ${{ secrets.GITHUB_TOKEN }}
-  #         report_paths: "*-test-results.xml"
+      - name: Publish Test Report
+        if: success() || failure()
+        uses: scacap/action-surefire-report@v1.0.7
+        continue-on-error: true
+        with:
+          check_name: Indy Plenum ${{ matrix.module }} Test Report for slice ${{ matrix.slice }}/${{ strategy.job-total }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          report_paths: "*-test-results.xml"
 
-  #     - name: Upload Detailed Test Failure Results
-  #       # The test runner only emits the detailed test results if the tests fail.
-  #       if: (steps.plenum-test.outcome == 'failure') && failure()
-  #       uses: actions/upload-artifact@v2
-  #       with:
-  #         name: detailed-test-result-slice-${{ matrix.slice }}
-  #         path: test-result-plenum-${{ matrix.slice }}.txt
-  #         retention-days: 5
+      - name: Upload Detailed Test Failure Results
+        # The test runner only emits the detailed test results if the tests fail.
+        if: (steps.plenum-test.outcome == 'failure') && failure()
+        uses: actions/upload-artifact@v2
+        with:
+          name: detailed-test-result-slice-${{ matrix.slice }}
+          path: test-result-plenum-${{ matrix.slice }}.txt
+          retention-days: 5
 
-  # indy_plenum_module_tests:
-  #   name: Module Tests
-  #   # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
-  #   needs: [workflow-setup, build-image]
-  #   runs-on: ubuntu-20.04
-  #   env:
-  #     UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
-  #   container:
-  #     image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-build:${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
-  #   strategy:
-  #     matrix:
-  #       module: [common, crypto, ledger, state, storage, stp_core, stp_zmq]
-  #     fail-fast: false
-  #   steps:
-  #     - name: Check out code
-  #       uses: actions/checkout@v2
+  indy_plenum_module_tests:
+    name: Module Tests
+    # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
+    needs: [workflow-setup, build-image]
+    runs-on: ubuntu-20.04
+    env:
+      UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
+    container:
+      image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-build:${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
+    strategy:
+      matrix:
+        module: [common, crypto, ledger, state, storage, stp_core, stp_zmq]
+      fail-fast: false
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
 
-  #     - name: Cache pip
-  #       uses: actions/cache@v2
-  #       with:
-  #         # pip cache on the plenum-build image is not in the default location.
-  #         # path: ~/.cache/pip
-  #         path: /root/.cache/pip
-  #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
-  #         restore-keys: |
-  #           ${{ runner.os }}-pip-
+      - name: Cache pip
+        uses: actions/cache@v2
+        with:
+          # pip cache on the plenum-build image is not in the default location.
+          # path: ~/.cache/pip
+          path: /root/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-
 
-  #     - name: Install dependencies
-  #       run: |
-  #         # Explicitly use the existing pip cache location in the plenum-build image.
-  #         pip --cache-dir /root/.cache/pip install .[tests]
+      - name: Install dependencies
+        run: |
+          # Explicitly use the existing pip cache location in the plenum-build image.
+          pip --cache-dir /root/.cache/pip install .[tests]
 
-  #     - name: Run Indy Plenum ${{ matrix.module }} tests
-  #       run: python3 -m pytest -l -vv --junitxml=test-result-plenum-${{ matrix.module }}.xml ${{ matrix.module }}
+      - name: Run Indy Plenum ${{ matrix.module }} tests
+        run: python3 -m pytest -l -vv --junitxml=test-result-plenum-${{ matrix.module }}.xml ${{ matrix.module }}
 
-  #     - name: Publish Test Report
-  #       uses: scacap/action-surefire-report@v1.0.7
-  #       continue-on-error: true
-  #       with:
-  #         check_name: Indy Plenum ${{ matrix.module }} Test Report
-  #         github_token: ${{ secrets.GITHUB_TOKEN }}
-  #         report_paths: test-result-plenum-${{ matrix.module }}.xml
+      - name: Publish Test Report
+        uses: scacap/action-surefire-report@v1.0.7
+        continue-on-error: true
+        with:
+          check_name: Indy Plenum ${{ matrix.module }} Test Report
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          report_paths: test-result-plenum-${{ matrix.module }}.xml
 
-  # lint:
-  #   name: Lint
-  #   # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
-  #   needs: [workflow-setup, lint-image]
-  #   runs-on: ubuntu-20.04
-  #   env:
-  #     UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
-  #   container:
-  #     image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-lint:${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
-  #   steps:
-  #     - name: Check out code
-  #       uses: actions/checkout@v2
+  lint:
+    name: Lint
+    # Reference to workflow-setup job is required to access the GITHUB_REPOSITORY_NAME output.
+    needs: [workflow-setup, lint-image]
+    runs-on: ubuntu-20.04
+    env:
+      UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
+    container:
+      image: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/plenum-lint:${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
 
-  #     - name: flake8
-  #       run: python3 -m flake8
+      - name: flake8
+        run: python3 -m flake8
 
   build_release:
     name: Build Release
-    # needs: [workflow-setup, indy_plenum_tests, indy_plenum_module_tests, lint]
-    needs: [workflow-setup, build-image]
+    needs: [workflow-setup, indy_plenum_tests, indy_plenum_module_tests, lint]
+    # needs: [workflow-setup, build-image]
     runs-on: ubuntu-20.04
     env:
       UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
@@ -377,8 +377,8 @@ jobs:
 
   build_3rd_party_dependencies:
     name: Build 3rd Party Dependencies
-    # needs: [workflow-setup, indy_plenum_tests, indy_plenum_module_tests, lint]
-    needs: [workflow-setup, build-image]
+    needs: [workflow-setup, indy_plenum_tests, indy_plenum_module_tests, lint]
+    # needs: [workflow-setup, build-image]
     runs-on: ubuntu-20.04
     env:
       UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
@@ -406,7 +406,7 @@ jobs:
     name: Publish Artifacts
     runs-on: ubuntu-20.04
     needs: [workflow-setup, build_release, build_3rd_party_dependencies]
-    # if: needs.workflow-setup.outputs.publish == 'true'
+    if: needs.workflow-setup.outputs.publish == 'true'
     env:
       GITHUB_REF: ${{ needs.workflow-setup.outputs.GITHUB_REF }}
       UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
